### ISSUE TITLE
Failed to resolve: com.github.YangDai2003:GifEncoderLib:1.0.5

### ISSUE THREAD

**Issue by wasimmemon0786** [YangDai2003/ImageCraft-Android#1]
Failed to resolve: com.github.YangDai2003:GifEncoderLib:1.0.5

**Comment by YangDai2003** [comment]
Please read the readme of https://github.com/YangDai2003/GifEncoderLib carefully and check whether the Gradle configuration is correct.

> Failed to resolve: com.github.YangDai2003:GifEncoderLib:1.0.5

**Comment by wasimmemon0786** [comment]
remove this librery to use projuct
