### ISSUE TITLE
Make the compressed images having same name as original

### ISSUE THREAD

**Issue by NikunjK8** [YangDai2003/ImageCraft-Android#3]
Currently the compressed images name get changed completely. I like to organise my pictures with naming schemes and i have to manually rename them one by one after compressing. Please make the compress images have the same name as original with extra text added (like ImageCraft) to differentiate them and prevent the original image from getting replaced. Thank you

**Comment by YangDai2003** [comment]
> 目前，压缩图像名称已完全更改。我喜欢用命名方案来组织我的图片，压缩后我必须手动将它们一一重命名。请使压缩图像与原始图像具有相同的名称，并添加额外的文本（如 ImageCraft）以区分它们并防止原始图像被替换。谢谢

Thank you for your suggestion. The new naming method has been changed and will use the format of original image name + date + application name, such as "Sun_20240317_151101_ImageCraft".

**Comment by NikunjK8** [comment]
Thank you for the quick response :)
